-- Schemas (docs/plan.md §3.3). Tables arrive with the stage that needs them:
--   gold.*     the source of truth this system reads (standalone: generated by synth/; integrated: from
--              m3-trusted-data-foundation). Never written by narration or by an action.
--   metrics.*  daily metric tables computed by plain SQL in metrics/sql/, one row per date and segment.
--   ops.*      control plane: runs, model calls, tool calls, drafted actions, mock Jira.

CREATE SCHEMA gold;
CREATE SCHEMA metrics;
CREATE SCHEMA ops;

COMMENT ON SCHEMA gold IS 'Governed delivery, production and inventory facts this system reads. Read-only here.';
COMMENT ON SCHEMA metrics IS 'Daily metrics computed in SQL. Code calculates; the model only ever narrates these.';
COMMENT ON SCHEMA ops IS 'Control plane: runs, LLM and tool calls, drafted actions, approvals, mock tickets.';
