"""Walk the history day by day with the detectors, score the result, write the report.

No LLM runs here by default (plan B13): a replay is about whether the *detection* is any good, and narrating
500 days would cost money to measure nothing. What comes out is the honest floor of the system — the numbers
the rest of the project is allowed to claim.

The report is generated, never hand-written, and it prints the failures as prominently as the totals.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import date, timedelta
from pathlib import Path

import pandas as pd

from detect.attribute import attribute
from detect.config import DetectConfig
from detect.models import Anomaly, Severity
from detect.run import build_series, detect_range, warmup_start, window_for
from replay.scoring import Event, ScoreCard, brief_view, matches, score, to_events

TARGETS = {"recall": 0.90, "precision": 0.80, "attribution_accuracy": 0.85}


@dataclass
class ReplayResult:
    card: ScoreCard
    events: list[Event]
    anomalies: list[Anomaly]

    @property
    def met_targets(self) -> dict[str, bool]:
        return {"recall": self.card.recall >= TARGETS["recall"],
                "precision": self.card.precision >= TARGETS["precision"],
                "attribution_accuracy": self.card.attribution_accuracy >= TARGETS["attribution_accuracy"],
                "decoy_not_raised": self.card.decoy_high_events == 0}


def replay(frames: dict[str, pd.DataFrame], cfg: DetectConfig, specs: list[dict],
           from_date: date | None = None, to_date: date | None = None,
           brief_items_per_day: int = 6) -> ReplayResult:
    first, last = window_for(frames)
    start = from_date or warmup_start(frames, cfg)
    end = to_date or last
    if start < first:
        start = first

    series = build_series(frames, cfg)
    anomalies = detect_range(series, cfg, start, end)
    events = to_events(anomalies)
    card = score(events, specs, (start, end))
    card.brief_items, card.brief_true_positives = brief_view(events, specs, brief_items_per_day)
    _attribute_findings(frames, cfg, events, specs, card)
    return ReplayResult(card=card, events=events, anomalies=anomalies)


def _attribute_findings(frames: dict[str, pd.DataFrame], cfg: DetectConfig, events: list[Event],
                        specs: list[dict], card: ScoreCard) -> None:
    """Did the decomposition name the segment the generator broke? Only asked where it could be answered.

    An anomaly detected only at its own finest grain has nothing to decompose — the segment is already named —
    so it is not scored. Scoring it as correct would inflate the number with cases nobody was asked about.
    """
    by_id = {s["anomaly_id"]: s for s in specs}
    for finding in card.findings:
        spec = by_id[finding.anomaly_id]
        seeded = {k: v for k, v in spec["segment"].items() if v != "ALL"}
        if not finding.detected or not seeded:
            continue
        coarse = [e for e in events if matches(e, spec) and set(e.segment) < set(seeded)]
        if not coarse:
            finding.note = "detected at the seeded grain; nothing coarser to decompose"
            continue
        event = max(coarse, key=lambda e: (e.peak_severity, e.peak_rank))
        result = attribute(frames, cfg, event.peak)
        if not result.drivers:
            finding.driver_correct = False
            finding.note = result.note
            continue
        top = result.drivers[0]
        finding.top_driver = top.label
        finding.driver_correct = all(top.segment.get(k) == v for k, v in seeded.items()
                                     if k in top.segment)


def split_scores(frames: dict[str, pd.DataFrame], cfg: DetectConfig, specs: list[dict],
                 split: date) -> tuple[ReplayResult, ReplayResult]:
    """The same replay, run either side of a date.

    The detection floors in policy.yaml were set by looking at the first half. Reporting only the combined
    number would hide that: a threshold chosen because it suppressed a particular false positive will always
    look good on the days it was chosen from. The second half was never used for tuning, so its numbers are
    the ones to believe.
    """
    first, last = window_for(frames)
    return (replay(frames, cfg, specs, warmup_start(frames, cfg), split),
            replay(frames, cfg, specs, split + timedelta(days=1), last))


def write_report(result: ReplayResult, cfg: DetectConfig, path: Path, json_path: Path | None = None,
                 split: tuple[ReplayResult, ReplayResult] | None = None,
                 specs: list[dict] | None = None) -> None:
    card = result.card
    met = result.met_targets
    lines = [
        "# Replay report",
        "",
        "Generated by `make replay` (`replay/run_replay.py`). Detection only — no LLM runs in a replay.",
        f"Window **{card.window[0]} .. {card.window[1]}** "
        f"({(card.window[1] - card.window[0]).days} days), scored against `ground_truth/anomalies.json`.",
        "",
        "## Headline",
        "",
        "| Measure | Result | Target | Met |",
        "|---|---|---|---|",
        _row("Detection recall (WARN+)", f"{card.recall:.0%}", "90%", met["recall"]),
        _row("Precision (HIGH events)", f"{card.precision:.0%}", "80%", met["precision"]),
        _row("Attribution top-1", f"{card.attribution_accuracy:.0%}", "85%", met["attribution_accuracy"]),
        _row("Holiday decoy raised HIGH", f"{card.decoy_high_events} events", "0", met["decoy_not_raised"]),
        _row("Median lead time",
             f"{card.median_lead_time:.0f} days" if card.median_lead_time is not None else "—",
             "reported", True),
        _row("Brief precision (top 6/day)", f"{card.brief_precision:.0%}", "reported", True),
        "",
        f"Events: **{card.events}** at WARN or above, of which **{card.high_events}** reached HIGH — "
        f"{card.true_positive_events} matching a seeded anomaly, {card.false_positive_events} not "
        f"({card.false_positives_per_day:.2f} a day). Of the {card.brief_items} items a person would have "
        f"been shown at six a day, {card.brief_true_positives} were real.",
        "",
        "## Per seeded anomaly",
        "",
        "| ID | Metric | Expected | Detected | Peak | Lead time | Events | Top driver | Driver correct |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for f in card.findings:
        lead = f"{f.lead_time_days} d" if f.lead_time_days is not None else "—"
        driver = f.top_driver or ("—" if f.driver_correct is None else "none")
        correct = "—" if f.driver_correct is None else ("yes" if f.driver_correct else "**no**")
        expected = "yes" if f.expect_detection else "no (decoy)"
        detected = "yes" if f.detected else "**no**"
        lines.append(f"| {f.anomaly_id} | {f.metric} | {expected} | {detected} | {f.peak_severity or '—'} | "
                     f"{lead} | {f.events} | {driver} | {correct} |")

    if split is not None and specs is not None:
        tuned, held = split
        lines += [
            "",
            "## Tuned on the first half, checked on the second",
            "",
            "The floors and thresholds in `policy.yaml` were chosen by looking at the first window. A "
            "threshold picked because it silenced a particular false positive will always look good on the "
            "days it was picked from. The second window was never used while tuning.",
            "",
            "| Window | Days | Seeded anomalies found | Precision | HIGH events | False positives |",
            "|---|---|---|---|---|---|",
        ]
        starts = {spec["anomaly_id"]: date.fromisoformat(spec["start"]) for spec in specs}
        for name, part in (("Tuning", tuned), ("Held out", held)):
            c = part.card
            mine = [x for x in c.findings if x.expect_detection
                    and c.window[0] <= starts[x.anomaly_id] <= c.window[1]]
            found, seeded_here = sum(1 for x in mine if x.detected), len(mine)
            lines.append(f"| {name} ({c.window[0]} .. {c.window[1]}) | {(c.window[1] - c.window[0]).days} | "
                         f"{found}/{seeded_here} | {c.precision:.0%} | {c.high_events} | "
                         f"{c.false_positive_events} |")
        lines.append("")
        lines.append("Seeded anomalies are counted where their own window falls; both halves see every "
                     "segment, so a false positive can land in either.")

    notes = [f for f in card.findings if f.note]
    if notes:
        lines += ["", "Notes:", ""] + [f"- **{f.anomaly_id}**: {f.note}" for f in notes]

    lines += [
        "",
        "## What the numbers do not say",
        "",
        "- Precision counts every HIGH event with no seeded anomaly behind it as wrong. Some of those are "
        "genuine movements in a random world — the generator seeds six anomalies but does not promise the "
        "other 529 days are flat. The number is therefore a floor, not an estimate of real-world precision.",
        "- Recall is measured at WARN and above; precision at HIGH. An event that stayed at WARN was "
        "recorded and never interrupted anyone.",
        "- Attribution is scored only where there was something coarser to decompose. Anomalies detected at "
        "the grain they were seeded at name their own segment, and are not counted either way.",
        "",
        "## Settings this run used",
        "",
        f"- baseline {cfg.baseline_days} days, day-of-week adjustment "
        f"{'on' if cfg.day_of_week_adjust else 'off'}, minimum {cfg.min_baseline_points} clean points",
        f"- z warn {cfg.z_warn}, z high {cfg.z_high}; CUSUM k={cfg.cusum_k}, h={cfg.cusum_h}",
        f"- holiday window ±{cfg.holiday_window_days} days, capped at {cfg.holiday_max_severity}; "
        f"findings with no policy breach capped at {cfg.statistical_max_severity}",
        "- floors: " + ", ".join(f"{k} vol≥{cfg.min_volume.get(k, 0):g}/move≥{cfg.min_magnitude.get(k, 0):g}"
                                 for k in sorted(cfg.thresholds)),
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    if json_path is not None:
        json_path.parent.mkdir(parents=True, exist_ok=True)
        json_path.write_text(json.dumps({"score": card.to_dict(),
                                         "events": [e.to_dict() for e in result.events]}, indent=2),
                             encoding="utf-8", newline="\n")


def _row(name: str, value: str, target: str, met: bool) -> str:
    return f"| {name} | **{value}** | {target} | {'yes' if met else '**NO**'} |"


def summarise(result: ReplayResult) -> str:
    card, met = result.card, result.met_targets
    missed = [name for name, ok in met.items() if not ok]
    verdict = "all targets met" if not missed else "MISSED: " + ",".join(missed)
    return (f"{card.window[0]}..{card.window[1]}: recall {card.recall:.0%} "
            f"precision {card.precision:.0%} attribution {card.attribution_accuracy:.0%} "
            f"lead {card.median_lead_time}d decoy_high {card.decoy_high_events} "
            f"[{verdict}]")


def load_specs(path: Path) -> list[dict]:
    return json.loads(path.read_text(encoding="utf-8"))["anomalies"]


def incidents_only(anomalies: list[Anomaly]) -> list[Anomaly]:
    return [a for a in anomalies if a.severity >= Severity.WARN]
